apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
  labels:
    app: webapp2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp2
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
        - image: dbhatia86/webapp2
          imagePullPolicy: Always
          name: webapp2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp2
  labels:
    app: webapp2
spec:
  type: LoadBalancer
  selector:
    app: webapp2
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP