version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.12.0

executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  lintcheck:
    executor: python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.devops
            . ~/.devops/bin/activate
            make install
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . ~/.devops/bin/activate
            make lint


  building-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build Docker Image 
          command: |
            docker login --username $docker_username --password $Docker_Pass
            docker build --tag=webapp1 .
            # Add the changes to the docker image
            docker-compose up -d
            # List docker images
            docker images
            # Push image to a docker repository
            docker tag webapp1 dbhatia86/webapp1
            docker push dbhatia86/webapp1


workflows:
  deployment:
    jobs:
      - lintcheck 
      - building-image           